CREATE TABLE product_category(
product_category_id serial PRIMARY KEY,
category_name varchar(255)
);

INSERT INTO product_category (category_name)
VALUES ('Chocolate'),
('Caramel'),
('Hard Candy'),
('Lollipops'),
('Gummies'),
('Bubblegum'),
('Cupcakes'),
('Cookies');

SELECT * FROM product_category;


CREATE TABLE products (
product_id serial PRIMARY KEY,
sku varchar(255),
ch_name varchar(255),
description varchar(255),
price decimal (13,2),
image_url varchar(255),
product_category_id_fk int REFERENCES product_category(product_category_id) 
);

INSERT INTO products (sku, ch_name, description, price, image_url, product_category_id_fk)
VALUES ('MILK-CHOCO-1000','Chocolate Truffel','Rich milk chocolate truffels. Yum!', 3.99, '/assets/images/products/Chocolate/ChocolateTruffles.png',1),
	('MILK-CHOCO-1001', 'Raspberry Truffels', 'Rich milk chocolate truffels with raspberry filling. Yum!', 3.99,'/assets/images/products/Chocolate/RaspberryTruffles.png' ,1),
	('MILK-CHOCO-1002', 'Chocolate Peanut Butter Truffles','Rich milk chocolate truffels with peanut butter filling. Yum!', 3.99,'/assets/images/products/Chocolate/ChocolatePeanutButterTruffles.png' ,1),
	('MILK-CHOCO-1003', 'Chocolate Caramel Truffles', 'Rich milk chocolate truffels with caramel filling. Yum!', 3.99, '/assets/images/products/Chocolate/ChocolateCaramelTruffles.png', 1),
	('MILK-CHOCO-1004', 'Chocolate Macademia Nut Truffles','Rich milk chocolate truffels with macedemia nuts. Yum!',3.99,'/assets/images/products/Chocolate/ChocolateMacadamiaNutTruffles.png',1),
	('MILK-CHOCO-1005', 'Chocolate Pumpkin Truffles', 'Rich pumpkin flavor. Yum!', 3.99, '/assets/images/products/Chocolate/PumpkinTruffles.png' ,1),
	('MILK-CHOCO-1006', 'Chocolate Turtle', 'Crunchy Pecans wrapped in gooey caramel with smooth milk chocolate shell', 3.99,'/assets/images/products/Chocolate/ChocolateTurtles.png' ,1),
	('MILK-CHOCO-1007', 'Milk Chocolate Bar', 'The best milk chocolate bar ever!', 3.99, '/assets/images/products/Chocolate/ChocolateBars.png' ,1),
	('MILK-CHOCO-1008', 'Chocolate Covered Marshmallows', 'Nothing goes better together than marshmallows and chocolate!',3.99,'/assets/images/products/Chocolate/ChocolateCoveredMarshmallows.png',1),
	('MILK-CHOCO-1009', 'Milk Chocolate Coconut Haystacks', 'Mountains of chocolatey delishious covered coconuts.',3.99,'/assets/images/products/Chocolate/MilkChocolateCoconutHaystack.png',1),
	('MILK-CHOCO-1010', 'Chocolate Malt Balls', 'Crunchy malt balls covered in creamy chocolate',3.99, '/assets/images/products/Chocolate/ChocolateMaltBalls.png',1),
	('MILK-CHOCO-1011','Dark Chocolate Almond Bark', 'The best bark you ever tasted.',3.99, '/assets/images/products/Chocolate/DarkChocolateAlmondBark.png' ,1),
	
	('CRML-CNDY-1000', 'Caramel squares', 'Delicious caramel squares.',3.99,'/assets/images/products/Caramel/CaramelSquares.png' , 2),
	('CRML-CNDY-1001', 'Foiled Caramel Candy', 'Caramel candy wrapped in foil',3.99,'/assets/images/products/Caramel/FoiledCaramel.png',2),
	('CRML-CNDY-1002', 'Caramel Cream Candy', 'Creamy caramel candy', 3.99,'/assets/images/products/Caramel/CaramelCreams.png',2),
	('CRML-CNDY-1003', 'Caramel Filled Chocolate Bites', 'Delicious chocolates filled with caramel', 3.99,'/assets/images/products/Caramel/CaramelFilledChocolates.png',2),
	('CRML-CNDY-1004', 'Hard Caramel Candy', 'Melt in your mouth delicious hard caramel candies', 3.99 , '/assets/images/products/Caramel/CaramelHardCandies.png', 2),
	('CRML-CNDY-1005', 'Peanut Butter Caramel Balls', 'Peanut Butter and caramel rolled into delicious treats.',3.99, '/assets/images/products/Caramel/PeanutButterCaramelBalls.png' ,2),
	('CRML-CNDY-1006','Caramel Apple Lollipops', 'Green apple lollipop covered in caramel.', 3.99, '/assets/images/products/Caramel/CaramelAppleCandies.png' ,2),
	('CRML-CNDY-1007', 'Caramel Fudge', 'Ooey, Gooey, delicious caramel fudge!', 3.99, '/assets/images/products/Caramel/CaramelFudge.png' ,2),
	('CRML-CNDY-1008', 'Caramel Vanilla Candy', 'Caramel candies with vanilla',3.99, '/assets/images/products/Caramel/CaramelVanillaCandies.png' ,2),
	('CRML-CNDY-1009','Caramel Marshmallow Candy','Caramel candies with marshmallow.',3.99, '/assets/images/products/Caramel/CaramelMarshmallowCandies.png' ,2),
	
	
	('HARD-CNDY-1001', 'Butterscotch', 'Individually wrapped butterscotch candies.', 1.99, '/assets/images/products/HardCandy/ButterscotchCandies.png' ,3),
	('HARD-CNDY-1002', 'Assorted Fruit Flavors', 'Individually wrapped fruit flavored candies.', 1.99, '/assets/images/products/HardCandy/AssortedFruitFlavorCandies.png' ,3),
	('HARD-CNDY-1003', 'Sour Strawberry Candy', 'Individually wrapped strawberry flavored sour candies.', 1.99, '/assets/images/products/HardCandy/SourCandies.png' ,3),
	('HARD-CNDY-1004', 'Jawbreakers', 'Hard as rock candy.', 1.99, '/assets/images/products/HardCandy/JawBreakers.png' ,3),
	('HARD-CNDY-1005', 'Lemon Drops', 'Sour lemon drop candies', 1.99, '/assets/images/products/HardCandy/Lemondrops.png' ,3),
	('HARD-CNDY-1006', 'Watermelon Candy', 'Hard watermelon flavored candy', 1.99, '/assets/images/products/HardCandy/WatermelonCandies.png' ,3),
	('HARD-CNDY-1007', 'Strawberry Candy', 'Individually wrapped strawberry hard candies', 1.99, '/assets/images/products/HardCandy/StrawberryCandies.png' ,3),
	('HARD-CNDY-1008', 'Root Beer Candy', 'Individually wrapped root beer hard candies', 1.99, '/assets/images/products/HardCandy/RootBeerCandies.png' ,3),
	('HARD-CNDY-1009', 'Mints', 'Individually wrapped peppermint candy', 1.99, '/assets/images/products/HardCandy/Mints.png' ,3),
	('HARD-CNDY-1010', 'Tarty Tarts', 'Tarty hard candy', 1.99, '/assets/images/products/HardCandy/TartyTarts.png' ,3),
	('HARD-CNDY-1011', 'Chocolate Mints', 'Individually wrapped chocolate mints', 1.99, '/assets/images/products/HardCandy/ChocolateMints.png' ,3),
	
	('LOLLI-POP-1000', 'Giant Lollipops','Colorful swirls of fun in all flavors! ', 2.50,'/assets/images/products/Lollipops/GiantLollipops.png',4),
		('LOLLI-POP-1001', 'Bubblegum Pops', 'Is it a lollipop? Is it bubblegum? Who knows!?',2.50, '/assets/images/products/Lollipops/BubblegumLollipop.png' ,4),
		('LOLLI-POP-1002', 'Chocolate Center Pops', 'Fruit flavored lollipops with chewy chocolate center',2.50, '/assets/images/products/Lollipops/ChocolateCenterLollipops.png' ,4),
		('LOLLI-POP-1003', 'Unicorn Pops', 'A lollipop that looks like a unicorn horn!', 2.50, '/assets/images/products/Lollipops/UnicornLollipops.png' ,4),
		('LOLLI-POP-1004', 'Sweet & Sour Pops', 'A lollipop that is sweet and sour.', 2.50, '/assets/images/products/Lollipops/SourLollipops.png' ,4),
		('LOLLI-POP-1005', 'Dum Dums', 'Any dum-dum knows these dum dums are super tasty!', 2.50, '/assets/images/products/Lollipops/DumDums.png' ,4),
		('LOLLI-POP-1006', 'Penguin Pops', 'Lollipops shaped like penguins!',2.50, '/assets/images/products/Lollipops/PenguinPops.png' ,4),
		('LOLLI-POP-1007', 'Ice Cream Lollies', 'Lollipops shaped like ice cream.',2.50, '/assets/images/products/Lollipops/IceCreamLollipops.png' ,4),
		('LOLLI-POP-1008', 'Smiley Face Pops', 'You will be happy after tasting this smiley face lollipop!',1.50, '/assets/images/products/Lollipops/SmileyFaceLollipops.png' ,4),
	
		--start at gummies next time--
		
	('GUMMY-CNDY-1000', 'Gummy Worms' , 'Deliciously disgusting gummy worms!' ,2.99, '/assets/images/products/Gummies/GummyWorms.png' ,5),
	('GUMMY-CNDY-1001', 'Sour Gummy Worms', 'Mouth puckering sour gummy worms.',2.99, '/assets/images/products/Gummies/SourGummyWorms.png' ,5),
	('GUMMY-CNDY-1002', 'Gummy Bears', 'The cutest gummies there are!', 2.99, '/assets/images/products/Gummies/GummyBears.png' ,5),
	('GUMMY-CNDY-1003', 'Sour Gummy Bears', 'These sweet bears will make you pucker!',2.99 , '/assets/images/products/Gummies/SourGummyBears.png' ,5),
	('GUMMY-CNDY-1004', 'Swedish Fish', 'Yummy gummy fish!' , 2.99, '/assets/images/products/Gummies/SwedishFish.png' , 5),
	('GUMMY-CNDY-1005', 'Sour Swedish Fish', 'Swedish fish -- but sour!',2.99, '/assets/images/products/Gummies/SourSwedishFish.png' ,5),
	('GUMMY-CNDY-1006', 'Fruit Chews', 'Fruit shaped gummies', 2.99, '/assets/images/products/Gummies/GummyFruit.png' ,5),
	('GUMMY-CNDY-1007', 'Strawberry Gummies', 'Strawberry flavored chews shaped like strawberries.',2.99, '/assets/images/products/Gummies/GummyStrawberries.png',5),
	('GUMMY-CNDY-1008', 'Spider Gummies', 'Your favorite snack just got creepier!', 2.99, '/assets/images/products/Gummies/GummySpiders.png' ,5),
	('GUMMY-CNDY-1009', 'Horse Gummies', 'Gummies shaped like a horse of course.',2.99, '/assets/images/products/Gummies/GummyHorses.png' ,5),
	('GUMMY-CNDY-1009', 'Jelly Beans', 'Fruit flavored jelly beans.',2.99, '/assets/images/products/Gummies/JellyBeans.png' ,5),
	
	('BUB-GUM-1000', 'Gumballs','Bubble chewing fun!', .50,'/assets/images/products/Bubblegum/Gumballs.png',6),
	('BUB-GUM-1001', 'Sour Gumballs', 'Can you handle this sour gum?',.50, '/assets/images/products/Bubblegum/SourGumballs.png' ,6),
	('BUB-GUM-1002', 'Smiley Gumballs', 'A happy piece of gum', .50, '/assets/images/products/Bubblegum/SmileyFaceBubbleGum.png' ,6),
	('BUB-GUM-1003', 'Bubblegum Squares', 'Colorful square shaped bubble gum.',.50, '/assets/images/products/Bubblegum/BubblegumSquares.png' ,6),
	('BUB-GUM-1004', 'Rainbow Bubblegum', 'Fun, rainbow colored bubblegun', .50, '/assets/images/products/Bubblegum/RainbowBubbleGum.png' ,6),
	('BUB-GUM-1005',  'Perfectly Pink Bubblegum', 'Pink strawberry, watermelon, and cherry flavored Bubblegum.', .50, '/assets/images/products/Bubblegum/PerfectlyPinkBubbleGum.png' ,6),
	('BUB-GUM-1006', 'Pop Rock Bubblegum', 'Bubble gum pop rocks.', .75, '/assets/images/products/Bubblegum/BubblegumPoprocks.png' ,6),
	('BUB-GUM-1007', 'Grape Gumballs', 'Grape flavored purple gumballs.', .50, '/assets/images/products/Bubblegum/GrapeGumballs.png' ,6),
	('BUB-GUM-1008', 'Blueberry Gumballs', 'Blueberry flavored blue gumballs.',.50, '/assets/images/products/Bubblegum/BlueberryGumballs.png' ,6),
	('BUB-GUM-1009', 'Watermelon Gumballs', 'Green watermelon flavored gumballs.', .50, '/assets/images/products/Bubblegum/WatermelonGumballs.png' ,6),
	
	
	('CUP-CAKES-1000', 'Raspberry Cupcakes', 'Delectable raspberry cupcakes', 3.99,'/assets/images/products/Cupcakes/RaspberryCupcakes.png' ,7),
	('CUP-CAKES-1001', 'Devils Food Cupcakes', 'Sumptuos devils food cake flavored cupcakes.', 3.99, '/assets/images/products/Cupcakes/DevilsFoodCupcakes.png' ,7),
	('CUP-CAKES-1002', 'Lemon Cupcakes', 'Zesty, sweet lemon cupcakes.', 3.99, '/assets/images/products/Cupcakes/LemonCupcakes.png' ,7),
	('CUP-CAKES-1003', 'Strawberry Cupcakes', 'Cute strawberry cupcakes.', 3.99, '/assets/images/products/Cupcakes/StrawberryCupcakes.png' ,7),
	('CUP-CAKES-1004', 'Blueberry Lemon Cupcakes', 'Tasty blueberry lemon cupcakes', 3.99, '/assets/images/products/Cupcakes/BlueberryCupcakes.png' ,7),
	('CUP-CAKES-1005', 'Funfetti Cupcakes', 'Colorful funfetti cupcakes are perfect for a party!', 3.99, '/assets/images/products/Cupcakes/FunfettiCupcakes.png' ,7),
	('CUP-CAKES-1006', 'Smore Cupcakes', 'You will want some more  of these smore cupcakes!', 3.99, '/assets/images/products/Cupcakes/SmoreCupcakes.png' ,7),
	('CUP-CAKES-1007', 'Almond Vanilla Cupcakes', 'Classic vanilla cupcakes with almonds.', 3.99, '/assets/images/products/Cupcakes/AlmondVanillaCupcakes.png' ,7),
	('CUP-CAKES-1008', 'Oreo Cupcakes', 'Cookies and cream cupcakes with oreos.', 3.99, '/assets/images/products/Cupcakes/OreoCupcakes.png' ,7),
	('CUP-CAKES-1009', 'Pumpkin Cupcakes', 'Pumpkin flavored cupcakes.',3.99, '/assets/images/products/Cupcakes/PumpkinCupcakes.png' ,7),
	
	
	('COOKIES-1000', 'Chocolate Chip Cookies', 'Just like homemade!', 3.99,'/assets/images/products/Cookies/ChocolateChipCookies.png',8),
	('COOKIES-1000', 'Sugar Cookies', 'Colorfully frosted sugar cookies to satisfy your sweet tooth!', 3.50, '/assets/images/products/Cookies/SugarCookies.png' ,8),
	('COOKIES-1000', 'Snickerdoodles', 'Flavorful snickerdoodle cookies.', 3.50, '/assets/images/products/Cookies/Snickerdoodles.png' ,8),
	('COOKIES-1000', 'Pumpkin Cookies', 'Pumpkin perfect cookies.', 3.50, '/assets/images/products/Cookies/PumpkinCookies.png' ,8),
	('COOKIES-1000', 'Sprinkle Cookies', 'Colorful cookies loaded with sprinkles.', 3.50, '/assets/images/products/Cookies/SprinkleCookies.png' ,8),
	('COOKIES-1000', 'Lemon Cookies', 'Lemon flavored cookies.', 3.50, '/assets/images/products/Cookies/LemonCookies.png' ,8),
	('COOKIES-1000', 'White Chocolate Macademia Nut Cookies', 'Cookies with white chocolate and macademia nuts.',3.50, '/assets/images/products/Cookies/WhiteChocolateMacademiaCookies.png', 8),
	('COOKIES-1000', 'Peanut Butter Cookies', 'Classic peanut butter flavored cookies.', 3.50, '/assets/images/products/Cookies/PeanutButterCookies.png' , 8),
	('COOKIES-1000', 'Strawberry Thumbprint', 'Cookies with strawberry filling.', 3.50, '/assets/images/products/Cookies/StrawberryThumbPrintCookies.png' ,8),
	('COOKIES-1000', 'Tripple Chocolate Cookies', 'Mega chocolatey cookies.', 3.950, '/assets/images/products/Cookies/TripleChocolateCookies.png' ,8),
	('COOKIES-1000', 'Salted Caramel Cookies', 'Chocolate chip cookies with salter caramel', 3.50, '/assets/images/products/Cookies/SaltedCaramelCookies.png', 8);
	
	
	

	
SELECT * FROM products;
			
CREATE TABLE users(
user_id serial PRIMARY KEY,
user_name varchar(255)
);



CREATE TABLE country (
country_id serial PRIMARY KEY,  
code varchar(2),
name_country varchar(255)
);



--
-- Data for table `country`
--

INSERT INTO country (code, name_country) 
VALUES
('BR','Brazil'),
('CA','Canada'),
('DE','Germany'),
('IN','India'),
('TR','Turkey'),
('US','United States');

SELECT * FROM country;

CREATE TABLE state (
  state_id serial PRIMARY KEY,
  name_state varchar(255) DEFAULT NULL,
 country_id_fk int REFERENCES country(country_id) 
);


--
-- Dumping data for table `state`
--

INSERT INTO state (state_id, name_state, country_id_fk) VALUES 
(1,'Acre',1),
(2,'Alagoas',1),
(3,'Amapá',1),
(4,'Amazonas',1),
(5,'Bahia',1),
(6,'Ceará',1),
(7,'Distrito Federal',1),
(8,'Espírito Santo',1),
(9,'Goiás',1),
(10,'Maranhão',1),
(11,'Mato Grosso do Sul',1),
(12,'Mato Grosso',1),
(13,'Minas Gerais',1),
(14,'Paraná',1),
(15,'Paraíba',1),
(16,'Pará',1),
(17,'Pernambuco',1),
(18,'Piaui',1),
(19,'Rio de Janeiro',1),
(20,'Rio Grande do Norte',1),
(21,'Rio Grande do Sul',1),
(22,'Rondônia',1),
(23,'Roraima',1),
(24,'Santa Catarina',1),
(25,'Sergipe',1),
(26,'São Paulo',1),
(27,'Tocantins',1),
(28,'Alberta',2),
(29,'British Columbia',2),
(30,'Manitoba',2),
(31,'New Brunswick',2),
(32,'Newfoundland and Labrador',2),
(33,'Northwest Territories',2),
(34,'Nova Scotia',2),
(35,'Nunavut',2),
(36,'Ontario',2),
(37,'Prince Edward Island',2),
(38,'Quebec',2),
(39,'Saskatchewan',2),
(40,'Yukon',2),
(41,'Baden-Württemberg',3),
(42,'Bavaria',3),
(43,'Berlin',3),
(44,'Brandenburg',3),
(45,'Bremen',3),
(46,'Hamburg',3),
(47,'Hesse',3),
(48,'Lower Saxony',3),
(49,'Mecklenburg-Vorpommern',3),
(50,'North Rhine-Westphalia',3),
(51,'Rhineland-Palatinate',3),
(52,'Saarland',3),
(53,'Saxony',3),
(54,'Saxony-Anhalt',3),
(55,'Schleswig-Holstein',3),
(56,'Thuringia',3),
(57,'Andhra Pradesh',4),
(58,'Arunachal Pradesh',4),
(59,'Assam',4),
(60,'Bihar',4),
(61,'Chhattisgarh',4),
(62,'Goa',4),
(63,'Gujarat',4),
(64,'Haryana',4),
(65,'Himachal Pradesh',4),
(66,'Jammu & Kashmir',4),
(67,'Jharkhand',4),
(68,'Karnataka',4),
(69,'Kerala',4),
(70,'Madhya Pradesh',4),
(71,'Maharashtra',4),
(72,'Manipur',4),
(73,'Meghalaya',4),
(74,'Mizoram',4),
(75,'Nagaland',4),
(76,'Odisha',4),
(77,'Punjab',4),
(78,'Rajasthan',4),
(79,'Sikkim',4),
(80,'Tamil Nadu',4),
(81,'Telangana',4),
(82,'Tripura',4),
(83,'Uttar Pradesh',4),
(84,'Uttarakhand',4),
(85,'West Bengal',4),
(86,'Andaman and Nicobar Islands',4),
(87,'Chandigarh',4),
(88,'Dadra and Nagar Haveli',4),
(89,'Daman & Diu',4),
(90,'Lakshadweep',4),
(91,'Puducherry',4),
(92,'The Government of NCT of Delhi',4),
(93,'Alabama',6),
(94,'Alaska',6),
(95,'Arizona',6),
(96,'Arkansas',6),
(97,'California',6),
(98,'Colorado',6),
(99,'Connecticut',6),
(100,'Delaware',6),
(101,'District Of Columbia',6),
(102,'Florida',6),
(103,'Georgia',6),
(104,'Hawaii',6),
(105,'Idaho',6),
(106,'Illinois',6),
(107,'Indiana',6),
(108,'Iowa',6),
(109,'Kansas',6),
(110,'Kentucky',6),
(111,'Louisiana',6),
(112,'Maine',6),
(113,'Maryland',6),
(114,'Massachusetts',6),
(115,'Michigan',6),
(116,'Minnesota',6),
(117,'Mississippi',6),
(118,'Missouri',6),
(119,'Montana',6),
(120,'Nebraska',6),
(121,'Nevada',6),
(122,'New Hampshire',6),
(123,'New Jersey',6),
(124,'New Mexico',6),
(125,'New York',6),
(126,'North Carolina',6),
(127,'North Dakota',6),
(128,'Ohio',6),
(129,'Oklahoma',6),
(130,'Oregon',6),
(131,'Pennsylvania',6),
(132,'Rhode Island',6),
(133,'South Carolina',6),
(134,'South Dakota',6),
(135,'Tennessee',6),
(136,'Texas',6),
(137,'Utah',6),
(138,'Vermont',6),
(139,'Virginia',6),
(140,'Washington',6),
(141,'West Virginia',6),
(142,'Wisconsin',6),
(143,'Wyoming',6),
(144,'Adıyaman',5),
(145,'Afyonkarahisar',5),
(146,'Ağrı',5),
(147,'Aksaray',5),
(148,'Amasya',5),
(149,'Ankara',5),
(150,'Antalya',5),
(151,'Ardahan',5),
(152,'Artvin',5),
(153,'Aydın',5),
(154,'Balıkesir',5),
(155,'Bartın',5),
(156,'Batman',5),
(157,'Bayburt',5),
(158,'Bilecik',5),
(159,'Bingöl',5),
(160,'Bitlis',5),
(161,'Bolu',5),
(162,'Burdur',5),
(163,'Bursa',5),
(164,'Çanakkale',5),
(165,'Çankırı',5),
(166,'Çorum',5),
(167,'Denizli',5),
(168,'Diyarbakır',5),
(169,'Düzce',5),
(170,'Edirne',5),
(171,'Elazığ',5),
(172,'Erzincan',5),
(173,'Erzurum',5),
(174,'Eskişehir',5),
(175,'Gaziantep',5),
(176,'Giresun',5),
(177,'Gümüşhane',5),
(178,'Hakkâri',5),
(179,'Hatay',5),
(180,'Iğdır',5),
(181,'Isparta',5),
(182,'İstanbul',5),
(183,'İzmir',5),
(184,'Kahramanmaraş',5),
(185,'Karabük',5),
(186,'Karaman',5),
(187,'Kars',5),
(188,'Kastamonu',5),
(189,'Kayseri',5),
(190,'Kırıkkale',5),
(191,'Kırklareli',5),
(192,'Kırşehir',5),
(193,'Kilis',5),
(194,'Kocaeli',5),
(195,'Konya',5),
(196,'Kütahya',5),
(197,'Malatya',5),
(198,'Manisa',5),
(199,'Mardin',5),
(200,'Mersin',5),
(201,'Muğla',5),
(202,'Muş',5),
(203,'Nevşehir',5),
(204,'Niğde',5),
(205,'Ordu',5),
(206,'Osmaniye',5),
(207,'Rize',5),
(208,'Sakarya',5),
(209,'Samsun',5),
(210,'Siirt',5),
(211,'Sinop',5),
(212,'Sivas',5),
(213,'Şanlıurfa',5),
(214,'Şırnak',5),
(215,'Tekirdağ',5),
(216,'Tokat',5),
(217,'Trabzon',5),
(218,'Tunceli',5),
(219,'Uşak',5),
(220,'Van',5),
(221,'Yalova',5),
(222,'Yozgat',5),
(223,'Zonguldak',5);

SELECT * FROM state;